---
# yamllint disable rule:line-length rule:truthy
os: linux
dist: focal
language: ruby
cache: bundler
before_install:
  - yes | gem update --system
  - bundle --version
script:
  - 'bundle exec rake $CHECK'
jobs:
  fast_finish: true
  include:
    - rvm: 2.4.4
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 5.0" CHECK=test
    - rvm: 2.5.3
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
    - rvm: 2.5.3
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
    - rvm: 2.4.4
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=centos8-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=centos8-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian10-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian10-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
      services: docker
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
  webhooks: https://voxpupu.li/incoming/travis
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  username: puppet
  password:
    secure: "bOrdAq112MG31oynJBjeIcbzIJ/ejLIDPXxFlZoK6DbVTKZxerY+Mdwvy2Dpc4WEjTvxkxmYJq0VHaRDkFBhLFmNBmiy/L7x4QzCmXXT6/p9DAQQj63u1HpQq6aBVuhPftOXE2Dfq44x0OUzIUUIOnQonpFN+YIfyafviZErnE2BjEazHa5jVBxxCG8wSEB+PqFMs2nQxjrRTAXX1BJU1HyEhzMIByJgy22jO51yXOW7mB/Gt5iCJnmVbeVk76Dm1RlqZ2RM0+Y/E0oCQN97YNBED6VAeqmt0hAo2lK+2SsoxRMueJVFBOQPH7r2s0CFGw9oPJN9/xiEF8cAxjXH9CKEBneb/dyYD6MuBXvpmdHvTdMTPGAASMavGqrR+Z0uILXPGv7Q4w4MOrIEKYQtiiovEqvOfiVz/JJO5TYoT1PGIF4EujzDnK9Aj6F0Gba+qtYy/AXcd0TFMxtyNd7bom+tVMWO4V2+puE8c76k9vyBseV32L653ZYV+BsHQi4wYiYNTTMA2KJmdORlxWaUYyhu9Ph/fWZ6/yDO/hr9dKddJ+g8d5qUA4H1sQPKVmjuOO5tmsq/MihOntqs+hDpX87E82jtkijhkoPEEk2QzLH4S2X63FTOVeWMdZOA4CFqZbzokLRFDceFInFseAYQC3NkvGWth7vAnFuUZlYFilU="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
